### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by bhie-23**
Information of the user can now be updated

### CODE REVIEW

**Comment by sunnygkp10** [comment]
@bhie-23 Please be specific about changes.

**Comment by bhie-23** [comment]
we add another code named update_action.php for updating the information of the user

**Comment by bhie-23** [comment]
You might wanna check it. We can't update the password because it's encrypted or what,.

**Comment by sunnygkp10** [comment]
undo the last commit and add only those file in commit which is changed or added by you.

**Pull request closed without merging**
